### ISSUE TITLE
Article non enregistré

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#42]
Aucune idée de pourquoi le beug est survenu, j'ai créé une brève, mis des tags, inséré une accroche avec un lien dans l'accroche, un lien où j'avais laissé le http:// en copiant-collant mon lien, du coup c'est peut-être ça qui a beugué je ne sais pas...
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0*
- platform : *Win32*
- outerWidth : *1294*
- innerWidth : *1280*

**Comment by lny** [comment]
WtF ?
