### ISSUE TITLE
Le "e" dans "coeur"

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#47]
Je ne sais plus comment cela s'appelle... mais en gros est-ce qu'il serait possible d'avoir des "e" correctement mis en forme pour dans les mots "coeur" "moeurs" etc. ? :-)
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0*
- platform : *Win32*
- outerWidth : *1294*
- innerWidth : *1280*

**Comment by lny** [comment]
Pour info, il y avait déjà au moment de la création de ce bug l'outil "Insérer un caractère spécial" dans CKEditor. C'est le symbole **Oméga**. Je les avais moi-même modifié pour ne conserver que les caractères spéciaux utiles dans un alphabet latin.
