### ISSUE TITLE
Erreur 404

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#49]
la page http://ourses-alpha.herokuapp.com/articles/éducation-culture/sexisme-dans-les-jeux-vid-eacute-os-une-critique-impossible-nbsp renvoità une erreur 404.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; rv:11.0) like Gecko*
- platform : *Win32*
- outerWidth : *1845*
- innerWidth : *1824*

**Comment by julie-petit** [comment]
Corrigé dans la version 1.0.3
