### ISSUE TITLE
enregistrement brouillon

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#51]
Salut, 
J'y pense, mais c'est juste une suggestion comme ça, est-ce que c'est compliqué/long à faire d'avoir des brouillons qui s'enregistrent tout seuls au bout de 10 secondes ? histoire d'éviter de perdre du temps pour les maladroites. 
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0*
- platform : *Win32*
- outerWidth : *1288*
- innerWidth : *1280*

**Comment by lny** [comment]
Heu ... ben y'a bien le plugin 'autosave' de CKEditor qui est censé enregistrer dans le localStorage à intervalle régulier tout le contenu de l'éditeur, mais en pratique il s'avère carrément moisi ... Il est par ailleurs activé (vraiment ? personne s'en est aperçu ?). Et quand bien même, ça ne résout pas le problème des autres informations.

Techniquement c'est possible, en pratique ça risque d'être plutôt long à mettre en place.

**Comment by lny** [comment]
Ok. Le plugin autosave de CKEditor a été réintégré, traduit, modifié et configuré de sorte qu'un brouillon non enregistré soit mis en mémoire à intervalle régulier (environ 10 secondes). La durée de vie du brouillon mis en mémoire est limitée à deux jours.
