### ISSUE TITLE
identification

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#52]
Quand je vais sur la page d'accueil du site "recette" le verrou du menu déroulant pour s'identifier n'apparaît pas, il faut que je clique sur une rubrique pour le voir, est-ce normal ?
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0*
- platform : *Win32*
- outerWidth : *1288*
- innerWidth : *1280*

**Comment by julie-petit** [comment]
corrigé en 1.0.3
