### ISSUE TITLE
gras, souligné, italique...

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#53]
gras, souligné, italique... possible ? (ou déjà le cas dans "recette" ?)
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0*
- platform : *Win32*
- outerWidth : *1288*
- innerWidth : *1280*

**Comment by julie-petit** [comment]
Ajouté en 1.0.3
