### ISSUE TITLE
Publication d'un article

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#54]
Après publication de plusieurs articles à des dates différentes, l'affichage des articles publiés par ordre antéchronologique n'est pas correct
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36*
- platform : *Win32*
- outerWidth : *1527*
- innerWidth : *1517*

**Comment by mathieu-bellange** [comment]
Corrigé dans la 1.0.3
