### ISSUE TITLE
Problème d'alignement liste des tags

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#55]
Dans la page de création/mise à jour d'un article, le champ "ajouter un tag" n'est pas aligné avec le bouton "+".
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Ok. C'est une petite erreur qui trouve sa source dans des classes globales ajoutées *a posteriori*.
