### ISSUE TITLE
le tooltip "Publier" reste visible

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#56]
Après la publication d'un article le tooltip "Publier" reste visible à l'endroit où il est apparu.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Ok. Tooltips Foundation supprimée.
