### ISSUE TITLE
La validation de modification de pseudo

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#57]
Après la validation de la modification d'un pseudo, la coche verte reste visible sous le rôle.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Ohhh !!! Le zoooliii bug ! C'est un un bon gros left-over lorsque j'ai refondu les classes de validation. Normalement l'icône n'apparaît pas du tout pour ce champ. Je corrige ça !

**Comment by lny** [comment]
Ok. J'en ai profité pour opérer le distingo entre champ vide et champ invalide dans la boîte d'erreur.
