### ISSUE TITLE
Affichage des coauteures

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#58]
Décalage entre l'auteur et la virgule (du au padding du a) en cas de coauteures.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Pas vraiment de solution convenable pour ce problème. Initialement, les séparateurs étaient générés par des pseudo-éléments CSS. L'espace intérieur était correctement géré, mais cela posait de graves problèmes d'alignement vertical selon le navigateur. Le correctif a été d'injecter les séparateurs par JavaScript, ce qui a permis d'uniformiser l'alignement vertical des séparateurs sur tous les navigateurs.
L'alternative possible pour la préservation de l'espacement entre les séparateurs et l'élément précédent c'est de supprimer l'espace intérieur en-dehors du survol de l'élément. Cette solution n'est pas idéale puisqu'elle oblige à rectifier l'alignement horizontal et donc à faire 'trembler' les éléments, d'où le choix qui a été fait de laisser cet espace intérieur, certes inélégant, mais ayant été considéré comme un moindre mal.
L'espace intérieur a néanmoins été rectifié pour que l'espacement entre le séparateur et l'élément soit préservé en-dehors du survol. Mais l'élément 'tremble' et le séparateur a été camouflé au survol de l'élément. Il faudra relancer le problème si cette solution n'est pas non plus satisfaisante.
