### ISSUE TITLE
Toolbar ckeditor

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#59]
Dans l'édition d'un article, la toolbar du ckeditor déborde en hauteur sur la rubrique.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Pas de contrôle sur la barre flottante de l'affichage en-page de CKEditor. Elle se positionne automatiquement en bas de l'éditeur si la hauteur du corps de l'article est supérieure à la hauteur de la page. Pour revenir à l'édition de la rubrique, de la catégorie ou des tags, il faut soit **cliquer en dehors du champ de l'éditeur**, soit **appuyer sur Shift+Tab**.
