### ISSUE TITLE
Suppression d'un article avec coauteures

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#60]
La suppression d'un article avec coauteures est impossible.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by mathieu-bellange** [comment]
Corrigé sur la 1.0.3
