### ISSUE TITLE
Renvoi d'un article d'une autre rédactrice

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#63]
Après le renvoi de l'article d'une autre rédactrice, l'article est visible comme brouillon alors que le filtre "Brouillons des autres" n'est pas activé.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Ok.
