### ISSUE TITLE
Confirmation lors de la suppression d'un compte

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#64]
Ajouter une popup de confirmation lors de la suppression d'un compte ?
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Ok. Possibilité de confirmer la suppression d'un compte ajoutée. Pas de confirmation pour l'instant (à configurer si besoin en réglant la variable globale **$conf.confirm_delete.account** à *true*).
