### ISSUE TITLE
Technique - XMLHttpRequest Deprecated

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#65]
La fonction synchro de XMLHttpRequest est deprecated. Voir pour la remplacer ?
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Lol.
