### ISSUE TITLE
Affichage de la page d'accueil

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#66]
Styles mal appliqués quand il n'y a pas de dernière revue du web.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36*
- platform : *Win32*
- outerWidth : *1600*
- innerWidth : *1600*

**Comment by lny** [comment]
Plus de dernière Revue du web. Pas de correction prévue.
