### ISSUE TITLE
Impossible de rentrer la description dans le profi

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#67]
Le champ pour la description dans le profil est accessible mais lorsque j'essaie de valider, un bandeau d'erreur apparait "Une erreur technique s'est produite" et le texte n'est pas enregistré...
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0*
- platform : *Win32*
- outerWidth : *1382*
- innerWidth : *1366*

**Comment by mathieu-bellange** [comment]
corrigé en 1.0.3, nullPointer
