### ISSUE TITLE
Problème sur les privilèges d'un compte

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#68]
J'ai créé un nouveau compte Ourse printanière à partir d'une adresse dédiée (ourse.printaniere), mais le statut "administratrice" est en grisé dans la liste des comptes à laquelle j'accède via chloe.sorbonne; et quand je me connecte avec ourse.printaniere, je n'ai qu'un statut de rédactrice...
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0*
- platform : *Win32*
- outerWidth : *1382*
- innerWidth : *1366*

**Comment by mathieu-bellange** [comment]
pb dû à des pseudos identiques, corrigé pour la 1.0.3
