### ISSUE TITLE
Mot de passe à faire une fois

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#71]
Salut,
J'ai créé plusieurs comptes et ce serait bien si ce n'est pas trop compliqué d'avoir la fonction "voir" le mot de passe qu'on écrit et/ou d'avoir à le confirmer, parce que là il faut juste taper un mot de passe qu'on ne voit pas à l'écran puis le valider, c'est un peu stressant ^^
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0*
- platform : *Win32*
- outerWidth : *1382*
- innerWidth : *1366*

**Comment by lny** [comment]
Ça ne devrait pas poser de problème.

**Comment by lny** [comment]
Ok.
