### ISSUE TITLE
Saut de ligne dans les bios

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#72]
Salut, comment faire pour que les sauts de lignes apparaissent dans les bios ? Quand je remplis ma bio dans le profil le saut de ligne apparaît en laissant un espace entre les deux lignes, mais ça disparaît ensuite quand c'est en ligne...
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; rv:11.0) like Gecko*
- platform : *Win32*
- outerWidth : *1384*
- innerWidth : *1368*

**Comment by lny** [comment]
C'est une tâche laissée en suspens, puis oubliée, merci de le rappeler :)

L'encodage des sauts des lignes et des caractères HTML n'a tout simplement pas encore été implémentée pour la modification du profil, elle le sera dans la prochaine version.

**Comment by lny** [comment]
Ok.
