### ISSUE TITLE
brouillon d'administratrice qui n'apparaît pas

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#73]
Salut,
L'autre jour j'ai créé un brouillon (FIFF ) que Chloé n'a pas vu apparaître dans sa liste d'articles, Est-ce que c'est normal ? Une administratrice ne peut pas relire et publier l'article d'une administratrice ou pas ? Mon brouillon est encore existant, donc vous pouvez le chercher. Chloé a publié du coup un autre article avec le même nom, qui a été publié dernièrement. A+
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; rv:11.0) like Gecko*
- platform : *Win32*
- outerWidth : *1384*
- innerWidth : *1368*

**Comment by mathieu-bellange** [comment]
Problème soit avec le cache soit avec le navigateur. L'intégralité des requêtes GET ont été revu pour gérer correctement le cache. Voir avec le navigateur qui semble provenir d'une Tablet PC

**Comment by lny** [comment]
Bug insolite. Pas de correction prévue.
