### ISSUE TITLE
enregistrements pas pris en compte

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#74]
De la même manière qu'un brouillon d'article n'apparaît pas tout de suite dans le back office une fois enregistré, mes modifications n'apparaissent pas... En gros faut enregistrer qu'à la fin si on veut pas attendre des heures derrière son ordi...
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; rv:11.0) like Gecko*
- platform : *Win32*
- outerWidth : *1384*
- innerWidth : *1368*

**Comment by mathieu-bellange** [comment]
Duplication avec le #73
