### ISSUE TITLE
Les articles des autres admins n'apparaissent pas

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#75]
Salut,
Petit souci technique? Quand je me connecte avec le compte de la Rédac ou le mien (Ourse printanière) je ne peux pas voir dans "mes articles" les articles proposés par Delphine (pas eu de test avec Anaïs); il faut donc qu'elle les valide elle-même. Est-ce que ça a à voir avec le fait qu'elle soit aussi admin? Car je vois bien les articles des autres rédactrices...
Merci bisous!
Chloé
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0*
- platform : *Win32*
- outerWidth : *1382*
- innerWidth : *1366*

**Comment by mathieu-bellange** [comment]
non reproduit
