### ISSUE TITLE
Le site n'apparaît pas correctement sur le navigateur Android

### ISSUE THREAD

**Issue by julie-petit** [mathieu-bellange/ourses-plumes#76]
En raison d'un Window (avec une majuscule) dans loap.js que le navigateur n'interprète pas, le corps du site n’apparaît pas.

**Comment by lny** [comment]
Étrange ... le seul 'Window' dans loap.js c'est une extension du prototype, et dans ce cas de figure la syntaxe est valide. J'opterais plutôt pour un problème avec la méthode 'checkCompatibility'. Affaire à suivre !

**Comment by mathieu-bellange** [comment]
C'est justement lui qui plante, erreur Window is undefined. Je corrige et faudra tester

**Comment by mathieu-bellange** [comment]
Corrigé pour la 1.1.0

**Comment by lny** [comment]
Arf ! Tu as été plus rapide :P
Si les essais ne sont pas concluants on pourra toujours détacher la fonction du prototype window (d'ailleurs je ne vois même pas pourquoi elle y est attachée ; la fonction est propre au document, pas à la fenêtre).
