### ISSUE TITLE
La recherche par tag ne fonctionne pas correctement

### ISSUE THREAD

**Issue by mathieu-bellange** [mathieu-bellange/ourses-plumes#78]
Quand on recherche les articles par un tag, tous les articles possédant ce tag ne remontent pas

**Comment by lny** [comment]
Vraisemblablement un problème de requête SQL. Si tu as envie de t'y coller, je ne dirais qu'une seule chose : bon courage ;)

Ce que j'en dis, c'est que ce qui n'est pas remonté aussi, c'est le problème. Alors je me permets d'appliquer en l'espèce ma principale devise (excellente au demeurant) : pas vu, pas pris ^^

Je ferme, tu ré-ouvriras si ça tu es pris d'une frénésie de débogage :)
