### ISSUE TITLE
lenteur d'affichage

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#79]
Salut, je ne sais pas si c'est propre à ma connexion aujourd'hui, mais la page "mes articles" s'affiche pas, faut que je m'acharne pour que cela se charge... Je ne sais pas d'ailleurs, si ça se trouve la lenteur est généralisée sur tout ce qu'on clique sur le site... rien de dramatique mais à surveiller au cas où ça se réitère.
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0*
- platform : *Win32*
- outerWidth : *1296*
- innerWidth : *1280*

**Comment by mathieu-bellange** [comment]
Travail sur la pagination de la requête

**Comment by lny** [comment]
Problème réglé sur la 1.2.0.
