### ISSUE TITLE
problème affichage

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#80]
Salut, en utilisant Firefox (dernière version, cache vidé...), avec mon netbook/tablette, je n'ai accès seulement à "mes articles" dans le menu déroulant, et n'ai pas la possibilité d'en écrire un nouveau. Par contre, cela marche avec Internet Explorer...
***
- appName : *Netscape*
- appCodeName : *Mozilla*
- userAgent : *Mozilla/5.0 (Windows NT 6.3; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; rv:11.0) like Gecko*
- platform : *Win32*
- outerWidth : *1384*
- innerWidth : *1368*

**Comment by lny** [comment]
Ce n'est pas un bug, c'est une restriction à l'utilisation mise en place pour limiter les fonctionnalités sur mobile et appareil à largeur d'écran réduite. **La largeur de la fenêtre du navigateur doit être supérieure à 800px** pour que les options d'administration autres que l'affichage de la liste des articles apparaissent.

Si ces options apparaissaient précédemment sur la tablette, l'hypothèse la plus vraisemblable c'est que la taille de la fenêtre du navigateur a changé.

Il convient donc de s'assurer :
1. Que le navigateur est ouvert en **plein écran**
2. Qu'il n'y a **pas de barre latérale** ouverte dans le navigateur (p. ex. marques pages ou historique)
