### ISSUE TITLE
guillemets dans les titres

### ISSUE THREAD

**Issue by ourses-plumes** [mathieu-bellange/ourses-plumes#84]
Salut, lorsque des guillemets sont mis dans les titres, ceux-ci beuguent et apparaissent tronqués lorsque l'on clique sur l'article pour entrer dedans. Et toute remodification du titre ne change rien si l'on laisse les guillemets. Il y a eu plusieurs fois des beugs sur les titres et il me semble que le dénominateur commun soit les guillemets. A surveiller si cela dépend d'autres choses.

---
- appName : _Netscape_
- appCodeName : _Mozilla_
- userAgent : _Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0_
- platform : _Win32_
- outerWidth : _1296_
- innerWidth : _1280_

**Comment by lny** [comment]
Ok. Là il y a effectivement un gros problème.

N'importe quel chaîne de caractère commençant par un guillemet-apostrophe (") est éjectée lorsqu'on ré-édite l'article.
*"fdsqjklm"* => *...*
*fdsq"jklm* => *jklm*

**SOLUTION** : Convertir tous les guillemets-apostrophes pairs d'un titre par des guillemets typographiques ouverts à gauche et tous les guillemets-apostrophes impairs d'un titre par des guillemets typographiques ouverts à droite.

**NOTE** : Il est possible d'utiliser les guillemets typographiques « et » - ou les guillemets de citation “ et ”

**Comment by ghost** [comment]
Ok. Problème résolu.
